### ISSUE TITLE
Add this for when there's no organization allow list - I overlooked this before

### ISSUE THREAD

**Issue by joncz** [KelvinTegelaar/AzGlue#3]
https://github.com/KelvinTegelaar/AzGlue/blob/f8c1c0cd523189f63ba6302a68bcec1a8ffcb97f/AzGluePS/AzGlueForwarder/run.ps1#L159

Insert
`        ($DISABLE_ORGLIST_CSV) -or`

at line 159

Test should read

    # For organization specific data, only return records linked to the authorized client.
    if ($itgRequest.data.type -contains "organizations" -or 
        $itgRequest.data[0].attributes.'organization-id') {
    
        $itgRequest.data = $itgRequest.data | Where-Object {
            ($DISABLE_ORGLIST_CSV) -or
            ($_.type -eq "organizations" -and $_.id -in $allowedOrgs.ITGlueOrgID) -or
            ($_.attributes.'organization-id' -in $allowedOrgs.ITGlueOrgID)
        }
    }

**Comment by KelvinTegelaar** [comment]
Implemented.
